language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD

script:
  - gulp lint:js
  - gulp lint:sass
  - npm run gulp patternlab:build

after_success:
  - ./scripts/publish.sh